<<<<<<< HEAD
name: Build and Deploy Site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pypdf
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Check documents directory
      run: |
        echo "Checking documents directory..."
        ls -la documents/ || echo "Documents directory is empty or doesn't exist"
        echo "Total PDF files: $(find documents/ -name "*.pdf" | wc -l)"
    
    - name: Process documents
      run: |
        echo "Processing documents..."
        python scripts/auto_update.py
        echo "Documents processed successfully"
        
        # Show results
        echo "Generated documents.json contains $(jq length data/documents.json) documents"
        ls -la data/
        ls -la dist/data/ || echo "dist/data not created yet"
    
    - name: Build website
      run: |
        echo "Building website..."
        npm run build
        echo "Website built successfully"
        
        # Verify build
        ls -la dist/
        echo "Final documents.json contains $(jq length dist/data/documents.json) documents"
    
    - name: Commit updated files
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add generated files
        git add data/documents.json data/processed_files.json dist/data/documents.json
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing updated document database..."
          git commit -m "Auto-update documents database [skip ci]"
          git push
        fi
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@v2
=======
name: Build and Deploy Site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pypdf
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Check documents directory
      run: |
        echo "Checking documents directory..."
        ls -la documents/ || echo "Documents directory is empty or doesn't exist"
        echo "Total PDF files: $(find documents/ -name "*.pdf" | wc -l)"
    
    - name: Process documents
      run: |
        echo "Processing documents..."
        python scripts/auto_update.py
        echo "Documents processed successfully"
        
        # Show results
        echo "Generated documents.json contains $(jq length data/documents.json) documents"
        ls -la data/
        ls -la dist/data/ || echo "dist/data not created yet"
    
    - name: Build website
      run: |
        echo "Building website..."
        npm run build
        echo "Website built successfully"
        
        # Verify build
        ls -la dist/
        echo "Final documents.json contains $(jq length dist/data/documents.json) documents"
    
    - name: Commit updated files
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add generated files
        git add data/documents.json data/processed_files.json dist/data/documents.json
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing updated document database..."
          git commit -m "Auto-update documents database [skip ci]"
          git push
        fi
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@v2
>>>>>>> d383fcdd2b2676b9a4a41783f227ffcc5b7a941b
